# Generated by Django 5.1.2 on 2024-10-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='title',
            new_name='descriptionimage',
        ),
    ]
