# Generated by Django 5.1.2 on 2024-11-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
